import Foundation
import UserNotifications
import StrandAnalytics

// MARK: - Target-zone coaching notifications
//
// The phone half of target-zone coaching: each wrist cue the `TargetZoneCoachRunner` delivers is mirrored as
// a local notification, so a phone on an arm band or a bike mount says the same thing the strap just did.
// `NotificationPresenter` already presents banners while the app is in the foreground.
//
// Every cue uses ONE stable identifier: a new cue replaces the previous one in Notification Center instead of
// stacking a workout's worth of them. The cadence itself is the coach's (state changes, cooldown, reminder) —
// this file never decides when to post, only what to say.
//
// Permission follows the StrainTargetNotifier / BatteryNotifier idiom: asked once when the wearer turns the
// coaching on (`requestAuthorization`), only CHECKED when posting, so a workout never raises a system prompt.
enum TargetZoneNotifier {
    /// The one identifier every target-zone notification is posted under (replace-in-place).
    static let identifier = "target-zone-coach"

    /// Title + body for a feedback toward `zone`. NOOP's own wording.
    static func copy(_ feedback: TargetZoneCoach.Feedback, zone: Int) -> (title: String, body: String) {
        switch feedback {
        case .below:
            return (String(localized: "Below Zone \(zone)"),
                    String(localized: "Increase the intensity to get back into Zone \(zone)."))
        case .enteredZone:
            return (String(localized: "Zone \(zone)"),
                    String(localized: "You're in Zone \(zone). Hold this pace."))
        case .above:
            return (String(localized: "Above Zone \(zone)"),
                    String(localized: "Lower the intensity to get back into Zone \(zone)."))
        }
    }

    /// The sound file each feedback plays (bundled in the iOS app, generated by Tools/zone_training_sounds.py):
    /// the pitch goes UP to say "more" and DOWN to say "less", so it reads without looking at the phone.
    static func soundName(for feedback: TargetZoneCoach.Feedback) -> String {
        switch feedback {
        case .below: return "zone-increase.wav"
        case .enteredZone: return "zone-in.wav"
        case .above: return "zone-decrease.wav"
        }
    }

    /// The spoken cue for a feedback (Settings › Notifications › Voice cues). English on purpose: short,
    /// fixed words recorded once by the system voice, so the same file plays every time.
    static func voicePhrase(for feedback: TargetZoneCoach.Feedback) -> String {
        switch feedback {
        case .below: return "Raise"
        case .enteredZone: return "In the zone"
        case .above: return "Lower"
        }
    }

    /// The spoken cue for an interval phase change.
    static func intervalVoicePhrase(for cue: TargetZoneCues.IntervalCue) -> String {
        switch cue {
        case .go: return "Go"
        case .rest: return "Rest"
        case .done: return "Done"
        }
    }

    /// The notification-sound file a phrase is rendered to, in Library/Sounds.
    static func voiceFileName(for phrase: String) -> String {
        "zone-voice-" + phrase.lowercased().replacingOccurrences(of: " ", with: "-") + ".caf"
    }

    /// Title + body for an interval phase change.
    static func intervalCopy(_ cue: TargetZoneCues.IntervalCue, zone: Int,
                             plan: IntervalPlan) -> (title: String, body: String) {
        let workMin = Int(plan.workSeconds / 60)
        let restMin = Int(plan.restSeconds / 60)
        switch cue {
        case .go(let round):
            return (String(localized: "Interval \(round) of \(plan.rounds)"),
                    String(localized: "Go! \(workMin) minutes in Zone \(zone)."))
        case .rest(let round):
            return (String(localized: "Rest"),
                    String(localized: "Easy for \(restMin) minutes. Next: interval \(round + 1) of \(plan.rounds)."))
        case .done:
            return (String(localized: "Intervals done"),
                    String(localized: "All \(plan.rounds) intervals complete. Cool down at an easy pace."))
        }
    }

    /// The sound for an interval phase change (bundled in the iOS app, generated by
    /// Tools/zone_training_sounds.py): a start signal to go, a calm falling chime to rest, a short fanfare
    /// when the session is done.
    static func intervalSoundName(for cue: TargetZoneCues.IntervalCue) -> String {
        switch cue {
        case .go: return "zone-go.wav"
        case .rest: return "zone-rest.wav"
        case .done: return "zone-done.wav"
        }
    }

    /// Ask up front, at the moment the wearer turns target-zone coaching on, so the system dialog never
    /// appears mid-workout. A no-op once the user has answered (the system does not prompt twice).
    static func requestAuthorization() {
        #if os(iOS)
        UNUserNotificationCenter.current()
            .requestAuthorization(options: [.alert, .sound]) { _, _ in }
        #endif
    }

    /// Post (or replace) the coaching notification. Only when the OS already authorized notifications — no
    /// second system prompt from here. No-op on macOS, matching the wrist alerts.
    static func post(_ feedback: TargetZoneCoach.Feedback, zone: Int) {
        #if os(iOS)
        let text = Self.copy(feedback, zone: zone)
        let center = UNUserNotificationCenter.current()
        center.getNotificationSettings { settings in
            guard settings.authorizationStatus == .authorized
                    || settings.authorizationStatus == .provisional else { return }
            let content = UNMutableNotificationContent()
            content.title = text.title
            content.body = text.body
            // iOS falls back to the default sound if the named file is missing from the bundle.
            let name = ZoneVoiceCues.readySoundName(for: voicePhrase(for: feedback)) ?? soundName(for: feedback)
            content.sound = UNNotificationSound(named: UNNotificationSoundName(name))
            content.threadIdentifier = identifier
            center.add(UNNotificationRequest(identifier: identifier, content: content, trigger: nil))
        }
        #endif
    }

    /// Post (or replace) an interval phase-change notification, under the same identifier as the zone cues
    /// so the newest coaching message is always the one on screen.
    static func postInterval(_ cue: TargetZoneCues.IntervalCue, zone: Int, plan: IntervalPlan) {
        #if os(iOS)
        let text = intervalCopy(cue, zone: zone, plan: plan)
        let sound = ZoneVoiceCues.readySoundName(for: intervalVoicePhrase(for: cue)) ?? intervalSoundName(for: cue)
        let center = UNUserNotificationCenter.current()
        center.getNotificationSettings { settings in
            guard settings.authorizationStatus == .authorized
                    || settings.authorizationStatus == .provisional else { return }
            let content = UNMutableNotificationContent()
            content.title = text.title
            content.body = text.body
            content.sound = UNNotificationSound(named: UNNotificationSoundName(sound))
            content.threadIdentifier = identifier
            center.add(UNNotificationRequest(identifier: identifier, content: content, trigger: nil))
        }
        #endif
    }

    /// Remove the last coaching notification once the workout ends, so a stale "Below Zone 2" does not
    /// outlive the session it was about.
    static func clear() {
        #if os(iOS)
        let center = UNUserNotificationCenter.current()
        center.removeDeliveredNotifications(withIdentifiers: [identifier])
        center.removePendingNotificationRequests(withIdentifiers: [identifier])
        #endif
    }
}
